---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: eds-game-for-ftp-game-jam-2022
  name: server-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eds-game-for-ftp-game-jam-2022
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        limited_memory: "no"
        gpu: "yes"
        gpu-vendor: "amd"
      containers:
        - name: xvfb
          image: kube-registry:5000/eds-game-for-ftp-game-jam-2022-xvfb:latest
        - name: server
          image: kube-registry:5000/eds-game-for-ftp-game-jam-2022-server:latest
          env:
            - name: DISPLAY
              value: "localhost:0"
          ports:
            - containerPort: 8080
          resources:
            limits:
              amd.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: eds-game-for-ftp-game-jam-2022
spec:
  selector:
    app: server
  ports:
    - name: server
      port: 8080
      targetPort: 8080
