---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: eds-game-for-ftp-game-jam-2022
  name: xvfb-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eds-game-for-ftp-game-jam-2022
  name: xvfb-deployment
  labels:
    app: xvfb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xvfb
  template:
    metadata:
      labels:
        app: xvfb
    spec:
      nodeSelector:
        limited_memory: "no"
      containers:
        - name: xvfb
          image: kube-registry:5000/eds-game-for-ftp-game-jam-2022-xvfb:latest
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: xvfb
  namespace: eds-game-for-ftp-game-jam-2022
spec:
  selector:
    app: xvfb
  ports:
    - name: xvfb
      port: 6000
      targetPort: 6000
